name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./poker-solver

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: Run benchmark
      run: cargo bench -- --output-format bencher | tee output.txt
      
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file-path: poker-solver/output.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        # 可选：添加警告阈值
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: true 